name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Setup xvfb
      run: sudo apt-get install -y xvfb

    - name: Run tests
      run: xvfb-run -a yarn test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Install vsce
      run: yarn global add vsce

    - name: Package extension
      run: vsce package

    - name: Publish to Marketplace
      uses: HaaLeo/publish-vscode-extension@v0.4.2
      with:
        pat: ${{ secrets.VSCE_PAT }}
        registryUrl: https://marketplace.visualstudio.com
        yarn: true
        dryRun: false
        noVerify: false