name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Install vsce
      run: yarn global add vsce

    - name: Package extension
      run: vsce package

    - name: Auto version bump
      id: version
      run: |
        echo "Bumping version..."
        yarn version --patch -m "v%v"
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "newVersion=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        git add package.json yarn.lock
        git commit -m "Bump version to $NEW_VERSION"
        git push origin main --tags

    - name: Create and publish a new release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: success() && github.ref == 'refs/heads/main'
      with:
        tag_name: ${{ steps.version.outputs.newVersion }}
        release_name: Release ${{ steps.version.outputs.newVersion }}
        draft: false
        prerelease: false

    - name: Publish to Marketplace
      uses: HaaLeo/publish-vscode-extension@v0.4.2
      if: success() && github.ref == 'refs/heads/main'
      with:
        pat: ${{ secrets.VSCE_PAT }}
        registryUrl: https://marketplace.visualstudio.com
        yarn: true
        dryRun: false
        noVerify: false
